version: '3.4'
services:
  frontend:
    container_name: react
    build:
      context: ../youtube
      dockerfile: Dockerfile
    environment:
      - MONGODB_URL=mongodb://admin:admin@mongo:27017/modaspaco
    ports:
      - '3000:3000'
    volumes:
      - ../youtube:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:4.1.6
    container_name: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ../mongodb/db:/data/db
      - ../mongodb/configdb:/data/configdb
 
  mongo-express:
    links:
      - mongo
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
      ME_CONFIG_BASICAUTH_USERNAME: modaspaco
      ME_CONFIG_BASICAUTH_PASSWORD: modaspaco
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
